###
# OUILOGIQUE.COM
##

project:
  type: website
  output-dir: _site
  post-render:
    - scripts/flatten-pages-to-root.sh
  resources:
    - pages/*/**
    - images/**/*

execute:
  enabled: false

website:
  title: "ouilogique"
  site-url: "https://ouilogique.com"
  search: false
  navbar:
    title: false
    right:
      - text: '<span class="material-symbols-outlined">home</span>'
        file: index.qmd
    left:
      - text: ""
    logo: ./images/site-logo.png
    logo-alt: ouilogique.com
    logo-href: /
    pinned: true
    background: "#1B1B1B"
    collapse: false
  page-footer:
    center:
      - text: '<p>Â© 2026 ouilogique.com</p><p><span class="material-symbols-outlined">home</span></p>'
        file: /
      # - icon: github
      #   href: https://github.com/NicHub

format:
  html:
    include-in-header:
      - includes/material-symbols.html
    theme:
      - cyborg
      - custom.scss
    toc: false
    smooth-scroll: false
